version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'taskmandb'
      MYSQL_USER: 'taskmanuser'
      MYSQL_PASSWORD: 'taskmanpassword'
      MYSQL_ROOT_PASSWORD: 'taskmanpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - taskmandb:/var/lib/mysql
# Names our volume
volumes:
  taskmandb: